services:
  - type: web
    name: stock-notifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GITHUB_TOKEN
        sync: false
      - key: POLYGON_API_KEY
        sync: false
      - key: GITHUB_USERNAME
        value: childtosmonkey-web
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_CLAIMS_EMAIL
        sync: false
